import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    // ── Getting Started ────────────────────────────────────────
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['intro', 'overview', 'setup', 'architecture'],
    },

    // ── Architecture Decisions ─────────────────────────────────
    {
      type: 'category',
      label: 'Architecture Decisions',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'adrs',
        },
      ],
    },

    // ── Features ───────────────────────────────────────────────
    {
      type: 'category',
      label: 'Features',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'features',
        },
      ],
    },

    // ── Engineering Stories ────────────────────────────────────
    {
      type: 'category',
      label: 'Engineering Stories',
      collapsed: false,
      items: [
        'stories/index',
        {
          type: 'category',
          label: 'Data Architecture',
          collapsed: false,
          items: [
            'stories/nates-missing-thousands',
            'stories/two-filing-cabinets',
            'stories/sams-invisible-bug',
          ],
        },
        {
          type: 'category',
          label: 'Real-Time Systems',
          collapsed: false,
          items: [
            'stories/azeez-in-the-tunnel',
            'stories/jons-duplicate-feed',
            'stories/the-reconnect-storm',
          ],
        },
        {
          type: 'category',
          label: 'Mutations & UX',
          collapsed: false,
          items: [
            'stories/sams-double-transfer',
            'stories/the-optimistic-chef',
          ],
        },
        {
          type: 'category',
          label: 'Architecture & Structure',
          collapsed: false,
          items: [
            'stories/nates-messy-flat',
          ],
        },
      ],
    },

    // ── Interview Preparation ──────────────────────────────────
    {
      type: 'category',
      label: 'Interview Preparation',
      collapsed: false,
      items: [
        'interview/index',
        'interview/system-design',
        'interview/data-and-state',
        'interview/real-time',
        'interview/react-architecture',
        'interview/behavioural',
      ],
    },
  ],
};

export default sidebars;
