export const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      items: ['intro', 'overview', 'setup', 'architecture'],
    },
    {
      type: 'category',
      label: 'Architecture Decisions',
      items: [
        {
          type: 'autogenerated',
          dirName: 'adrs',
        },
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Features',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'features',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Guides',
    //   items: ['guides/testing', 'guides/deployment'],
    // },
  ],
};